###Upload Attach
POST localhost:8081/attach/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwLnAubWFnYS56dmVyQGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIzIiwiaWF0IjoxNzcwOTg2MTQxLCJleHAiOjE3NzA5ODk3NDF9.L5beg1VbBdY9fv17Io0MGpVjIfNMBBkxnbBT03jJka5HlHWPUb3iEHQMVPjMYTDxXiJAPEgnhwRz5Bv7T1GGvQ

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="photo_5213046822614536067_y.jpg";

< D:\какуля\хацкер.jpg



###Open Attach
GET localhost:8081/attach/open/fa84e9f4-e42d-456c-97e3-5fc8216555fe.jpg
Content-Type:  application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwLnAubWFnYS56dmVyQGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIzIiwiaWF0IjoxNzcwOTg2MTQxLCJleHAiOjE3NzA5ODk3NDF9.L5beg1VbBdY9fv17Io0MGpVjIfNMBBkxnbBT03jJka5HlHWPUb3iEHQMVPjMYTDxXiJAPEgnhwRz5Bv7T1GGvQ
