### REGISTRATION
POST localhost:8081/auth/registration
Content-Type: application/json
Accept-Language: RU

{
  "name" : "Mexa" ,
  "username" : "+998337706673" ,
  "password" : "1221"
}

### VERIFICATION
GET http://localhost:8081/auth/registration/verification/{profileId}

### LOGIN
POST localhost:8081/auth/login
Content-Type: application/json
Accept-Language: RU

{
  "username" : "p.p.maga.zver@gmail.com" ,
  "password" : "12"
}