### REGISTRATION
POST localhost:8081/auth/registration
Content-Type: application/json
Accept-Language: RU

{
  "name" : "Mexa" ,
  "username" : "p.p.maga.zver@gmail.com" ,
  "password" : "1221"
}

### REGISTRATION
POST localhost:8081/auth/registration
Content-Type: application/json
Accept-Language: RU

{
  "name" : "nexa" ,
  "username" : "998337706673" ,
  "password" : "1221"
}

### sms verification
POST localhost:8081/auth/registration/sms-verification
Content-Type: application/json
Accept-Language: RU

{
  "phone" : "998337706673" ,
  "code" : "29871"
}



### VERIFICATION
GET http://localhost:8081/auth/registration/verification/{profileId}

### LOGIN
POST localhost:8081/auth/login
Content-Type: application/json
Accept-Language: EN

{
  "username" : "p.p.maga.zver@gmail.com" ,
  "password" : "123"
}

### Sms resend
POST localhost:8081/auth/registration/sms-verification-resend
Content-Type: application/json
Accept-Language: EN

{
  "phone" : "998337706673"
}
### LOGIN sms
POST localhost:8081/auth/registration/sms-verification
Content-Type: application/json
Accept-Language: RU

{
  "phone" : "+998337706673" ,
  "code" : "68842"
}


###  resent password
POST localhost:8081/auth/reset-password
Content-Type: application/json
Accept-Language: EN

{
  "username" : "998337706673"
}



###  resent password confirm
POST localhost:8081/auth/reset-password-confirm
Content-Type: application/json
Accept-Language: EN

{
  "username" : "998337706673",
  "code" : "69848",
  "password" : "69848"
}


### profile update detail
PUT http://localhost:8081/profile/detail
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwLnAubWFnYS56dmVyQGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIyIiwiaWF0IjoxNzUzOTczMzczLCJleHAiOjE3NTM5NzY5NzN9.iHuaQPgQ_tTLOHPGorLY-zn6C4_CgK1dSj7fhTrUipBE95wOpYJV18JvpaoQ2Fa3mLBdyOpxA-O9TD4kNFgapQ

{
  "name": "Dizzerrrrrooooooooooooooooooo"
}

### profile update password
PUT http://localhost:8081/profile/updatePswd
Content-Type: application/json
Accept-Language: EN
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJwLnAubWFnYS56dmVyQGdtYWlsLmNvbSIsInJvbGVzIjoiUk9MRV9VU0VSIiwiaWQiOiIyIiwiaWF0IjoxNzU0NDc4MzM1LCJleHAiOjE3NTQ0ODE5MzV9.yNGQsGYCXVdbfcSmw7ty34lROWp504fwvfXgrqcFcB3Gy2Gv1yoKfCuLVcVgUhHP_Lmf5Y487-3ejr95GFtN-Q

{
  "oldPassword": "11111",
  "newPassword": "123"
}